# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: AnakinSkywalker0.blackbox
PackageVersion: 0.3.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-02
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AnakinSkywalker0/blackbox/releases/download/v0.3.0/bb-v0.3.0-setup-x64.exe
  InstallerSha256: EDC9FCF5ED7365A091CCCE4A2E75588FAA7D3B9807A2E83CB4967C3E7E00EFED
  ProductCode: '{6F291038-731F-4998-AADF-C25DCFC0032C}_is1'
ManifestType: installer
ManifestVersion: 1.10.0
