# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: AnakinSkywalker0.blackbox
PackageVersion: 0.4.2
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AnakinSkywalker0/blackbox/releases/download/v0.4.2/bb-v0.4.2-setup-x64.exe
  InstallerSha256: 87FAA4F132B10C403BB6B99A1F8C92F0D7264463A1718F8EAA10BCB9D5DCA08D
  ProductCode: '{6F291038-731F-4998-AADF-C25DCFC0032C}_is1'
ManifestType: installer
ManifestVersion: 1.10.0
